[package]
name = "rustxterm-ssh"
description = "SSH and SFTP protocol handler for RustXterm"
version.workspace = true
edition.workspace = true

[dependencies]
rustxterm-core = { path = "../rustxterm-core" }
russh = { workspace = true }
russh-keys = { workspace = true }
russh-sftp = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
